### ISSUE TITLE
Error getting player summaries for non-friend users

### ISSUE THREAD

**Issue by yzl210** [KnoxZZ/rsteam#2]
When a Steam user is not friends with the user owning the API key, the response will not contain `lastlogoff`.
https://github.com/kallekankaanpaa/rsteam/blob/abad9cf90e2a719ad520b451c0011113b7c26dcb/src/steam_user/get_player_summaries.rs#L78
This should be `Option<u32>`

**Comment by kallekankaanpaa** [comment]
Hi, thanks for opening the issue.

Has it been documented somewhere that the response doesn't contain `lastlogoff` when the Steam user isn't friends with the owner of the API key? Or could it have something to do with the privacy settings of the  Steam user?

In any case if `last_logoff` can be missing from the response it needs to be optional just as you pointed out.

**Comment by yzl210** [comment]
I don’t think it’s documented, but you can just test it by simply opening an offline friend’s profile and an offline non-friend's profile, in which you’ll see the difference

**Comment by kallekankaanpaa** [comment]
I fixed this issue (and a couple of other issues with the `get_player_summaries`) and bumped the version number up to `0.2.0`.
